spring: 
  jackson:  #json格式化配置
    date-format: yyyy-MM-dd
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
#输出sql日志 debug用
logging:
  level:
    org.springframework.web: TRACE
