spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Divoter/SpringCloudFrameStudy.git
          search-paths: /config-repo
          #本地仓库地址
          basedir: D:\GitHubRepository\SpringCloudFrameStudy
  rabbitmq:
    port: 5672
#    host: 192.168.187.128
    host: 192.168.0.111
    username: admin
    password: admin

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/ #,http://localhost:8001/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
server:
  port: 8686

#使日志显示接口映射信息
logging:
  level:
    org.springframework.web: TRACE
management:
  endpoints:
    web:
      exposure:
        include: "*"
