spring:
  application:
    name: zuulfilter #微服务名称
  profiles:
    active: test1   #当前环境
  jackson:  #json格式化配置
    date-format: yyyy-MM-dd
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false

eureka:
  client:
    service-url:  #注册中心
      defaultZone: http://localhost:8000/eureka/,http://localhost:8001/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

#输出sql日志 debug用
logging:
  level:
    com.divoter.${spring.application.name}: debug


#自定义路由转发，默认通过微服务名称转发
zuul:
  routes:
    myProduct: #自定义路由转发名称名称,随便定义
      # /myProduct/list --> productserver/list
      path: /myProduct/** #定义要转发的路由规则
      serviceId: productserver #转发到的微服务名称
  ignored-patterns: #排除某些路由
    - /myProduct/list
    - /productserver/list
    - /**/product/info
  sensitive-headers:  #空设置，可以允许cookie传递